# Generated by Django 4.0.3 on 2023-03-10 12:51

import Stockify.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=16)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('stock_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('watchlist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stocks', Stockify.models.ArrayField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stockify.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stockify.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('no_of_shares', models.IntegerField()),
                ('price_of_purchase', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stockify.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stockify.customer')),
            ],
        ),
    ]
