# Generated by Django 4.1.4 on 2023-03-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stockify', '0004_alter_holdings_bidprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='bidPrice',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='bidPrice',
        ),
    ]
