# Generated by Django 4.1.4 on 2023-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockify', '0006_holdings_bidprice_stocktransaction_bidprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='bidPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='bidPrice',
            field=models.FloatField(null=True),
        ),
    ]
