# Generated by Django 4.0.3 on 2023-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockify', '0007_alter_holdings_bidprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='cash',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
