# Generated by Django 4.0.3 on 2023-03-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stockify', '0009_alter_stocktransaction_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='cash',
        ),
    ]
