# Generated by Django 4.0.3 on 2023-03-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stockify', '0011_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='bidPrice',
        ),
    ]
