# Generated by Django 4.0.3 on 2023-03-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockify', '0012_remove_holdings_bidprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='mtm',
            field=models.FloatField(default=0),
        ),
    ]
