# Generated by Django 4.0.3 on 2023-04-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stockify', '0013_balance_mtm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='mtm',
        ),
    ]
